# Generated by Django 4.2.7 on 2023-11-10 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='websiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Application Name', max_length=500)),
                ('logo', models.ImageField(upload_to='app_config/')),
                ('logo_width', models.IntegerField(blank=True, null=True)),
                ('invoice_logo', models.ImageField(blank=True, null=True, upload_to='app_config')),
                ('invoice_logo_width', models.IntegerField(blank=True, null=True)),
                ('favicon', models.ImageField(upload_to='app_config/')),
                ('author', models.CharField(blank=True, default='Author Name', max_length=200, null=True)),
                ('email_address', models.EmailField(blank=True, default='test@gmail.com', max_length=500, null=True)),
                ('phone_or_whatsapp', models.CharField(blank=True, default='88012454784', max_length=20, null=True)),
                ('price_ragne', models.CharField(blank=True, default='60$ to 7000$', max_length=50, null=True)),
                ('country', models.CharField(blank=True, default='Your Country', max_length=300, null=True)),
                ('address', models.CharField(blank=True, default='Your Address', max_length=700, null=True)),
                ('state', models.CharField(blank=True, default='Your State', max_length=200, null=True)),
                ('Zip', models.IntegerField(default=12345)),
                ('analytics_code', models.CharField(blank=True, default='GA_MEASUREMENT_ID', max_length=300, null=True)),
                ('facebook_pixel_code', models.TextField(blank=True, null=True)),
                ('facebook_chat_code', models.TextField(blank=True, null=True)),
                ('whatsapp_is_active', models.BooleanField(default=True)),
                ('messenger_is_active', models.BooleanField(default=True)),
                ('currency_name', models.CharField(default='USD', max_length=100)),
                ('currency_symbol', models.CharField(default='$', max_length=150)),
                ('twilio_sid', models.CharField(blank=True, max_length=500, null=True)),
                ('twilio_auth_token', models.CharField(blank=True, max_length=500, null=True)),
                ('twilio_from_number', models.CharField(blank=True, max_length=15, null=True)),
                ('custom_css', models.TextField(blank=True, null=True)),
                ('custom_js', models.TextField(blank=True, null=True)),
                ('footer_copyright', models.CharField(max_length=600)),
            ],
        ),
    ]
