# Generated by Django 4.2.7 on 2023-11-11 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='websitesetting',
            name='messenger_is_active',
        ),
        migrations.RemoveField(
            model_name='websitesetting',
            name='whatsapp_is_active',
        ),
    ]
