# Generated by Django 5.0 on 2023-12-29 18:02

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_remove_websitesetting_messenger_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='paymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ssl_commerze_store_id', models.CharField(blank=True, max_length=255, null=True)),
                ('ssl_commerze_store_pass', models.CharField(blank=True, max_length=255, null=True)),
                ('ssl_commerze_is_sandbox', models.BooleanField(default=False)),
                ('ssl_commerze_is_active', models.BooleanField(default=False)),
                ('paypal_client_id', models.CharField(blank=True, max_length=5000, null=True)),
                ('paypal_client_secret', models.CharField(blank=True, max_length=5000, null=True)),
                ('paypal_is_sandbox', models.BooleanField(default=False)),
                ('paypal_is_active', models.BooleanField(default=False)),
                ('stripe_publish_key', models.CharField(blank=True, max_length=5000, null=True)),
                ('stripe_secret_key', models.CharField(blank=True, max_length=5000, null=True)),
                ('stripe_is_sandbox', models.BooleanField(default=False)),
                ('stripe_is_active', models.BooleanField(default=False)),
                ('instamojo_api_key', models.CharField(blank=True, max_length=5000, null=True)),
                ('instamojo_auth_token', models.CharField(blank=True, max_length=5000, null=True)),
                ('instamojo_is_sandbox', models.BooleanField(default=False)),
                ('instamojo_is_active', models.BooleanField(default=False)),
                ('razorpay_api_key', models.CharField(blank=True, max_length=5000, null=True)),
                ('razorpay_api_secret', models.CharField(blank=True, max_length=5000, null=True)),
                ('razorpay_is_active', models.BooleanField(default=False)),
                ('offline_payment_instruction', ckeditor.fields.RichTextField()),
                ('offline_payment_is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='websitesetting',
            name='is_auto_invoice_enable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='websitesetting',
            name='is_enabled_for_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='websitesetting',
            name='is_purchasing_enable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='websitesetting',
            name='max_token',
            field=models.IntegerField(blank=True, default=150, null=True),
        ),
        migrations.AddField(
            model_name='websitesetting',
            name='openai_api',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
