# Generated by Django 5.0 on 2023-12-30 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_paymentmethod_websitesetting_is_auto_invoice_enable_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websitesetting',
            name='currency_name',
            field=models.CharField(blank=True, default='USD', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='websitesetting',
            name='currency_symbol',
            field=models.CharField(blank=True, default='$', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='websitesetting',
            name='favicon',
            field=models.ImageField(blank=True, null=True, upload_to='app_config/'),
        ),
        migrations.AlterField(
            model_name='websitesetting',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='app_config/'),
        ),
        migrations.AlterField(
            model_name='websitesetting',
            name='name',
            field=models.CharField(blank=True, default='Application Name', max_length=500, null=True),
        ),
    ]
