# Generated by Django 4.2.7 on 2023-11-10 10:35

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='crmCustomPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('slug', models.SlugField(blank=True, max_length=1000, null=True)),
                ('content', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.CreateModel(
            name='crmProjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('progress', models.IntegerField(blank=True, default=0, null=True)),
                ('slug', models.SlugField(blank=True, max_length=500, null=True)),
                ('project_type', models.CharField(choices=[('client_project', 'Client Project'), ('internal_project', 'Internal Project')], default='client_project', max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField()),
                ('deadline', models.DateField()),
                ('price', models.IntegerField()),
                ('label', models.CharField(blank=True, choices=[('started', 'Started'), ('completed', 'Completed'), ('new_customer', 'New Customer'), ('important', 'Important'), ('closed', 'Closed'), ('running', 'Running'), ('canceled', 'Canceled'), ('pending', 'Pending')], max_length=50, null=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authapp.guser')),
            ],
        ),
        migrations.CreateModel(
            name='crmServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_expense', models.DateField(blank=True, null=True)),
                ('category', models.CharField(blank=True, choices=[('rent/mortgage', 'Rent/Mortgage'), ('utilities', 'Utilities'), ('transportation', 'Transportation'), ('food_and_dining', 'Food and Dining'), ('insurance', 'Insurance'), ('taxes', 'Taxes'), ('debt_payments', 'Debt Payments'), ('healthcare_and_medical_expenses', 'Healthcare and Medical Expenses'), ('miscellaneous_expenses', 'Miscellaneous Expenses'), ('personal_care', 'Personal Care'), ('fees', 'Fees'), ('others', 'Others')], max_length=300, null=True)),
                ('title', models.CharField(max_length=500)),
                ('slug', models.SlugField(blank=True, max_length=500, null=True)),
                ('amount', models.FloatField()),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('number', models.CharField(blank=True, max_length=100, null=True)),
                ('billDate', models.DateField(blank=True, null=True)),
                ('dueDate', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('UNPAID', 'UNPAID'), ('PAID', 'PAID')], default='UNPAID', max_length=100)),
                ('discount_amount', models.FloatField(default=0)),
                ('tax_amount', models.FloatField(default=0)),
                ('other_fees_name', models.CharField(blank=True, default='Other Fees', max_length=300, null=True)),
                ('other_fees_amount', models.FloatField(default=0)),
                ('notes', models.TextField(blank=True, null=True)),
                ('uniqueId', models.CharField(blank=True, max_length=100, null=True)),
                ('slug', models.SlugField(blank=True, max_length=500, null=True, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authapp.guser')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.crmprojects')),
            ],
        ),
        migrations.CreateModel(
            name='itemCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('slug', models.SlugField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='YearlyPaymentStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(unique=True)),
                ('total_payment', models.BigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_file', models.FileField(upload_to='project_files/')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.crmprojects')),
            ],
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('slug', models.SlugField(blank=True, max_length=200, null=True)),
                ('payment_method', models.CharField(blank=True, max_length=300, null=True)),
                ('payment_ammount', models.FloatField(blank=True, null=True)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('payment_note', models.TextField(blank=True, null=True)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='crm.invoice')),
            ],
        ),
        migrations.CreateModel(
            name='items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('slug', models.SlugField(blank=True, max_length=300, null=True, unique=True)),
                ('description', models.TextField()),
                ('unit_type', models.CharField(max_length=100)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('rate', models.FloatField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.itemcategory')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='crm.invoice')),
            ],
        ),
        migrations.CreateModel(
            name='crmTasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(blank=True, max_length=300, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('to_do', 'To do'), ('in_progress', 'In progress'), ('done', 'Done')], default='to_do', max_length=50)),
                ('priority', models.CharField(blank=True, choices=[('minor', 'Minor'), ('major', 'Major'), ('critical', 'Critical'), ('blocker', 'Blocker')], max_length=50, null=True)),
                ('label', models.CharField(blank=True, choices=[('started', 'Started'), ('completed', 'Completed'), ('new_customer', 'New Customer'), ('important', 'Important'), ('closed', 'Closed'), ('running', 'Running'), ('canceled', 'Canceled'), ('pending', 'Pending')], max_length=50, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.crmprojects')),
            ],
        ),
    ]
