# Generated by Django 5.0 on 2023-12-29 18:02

import ckeditor.fields
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='items',
            old_name='quantity',
            new_name='fake_sales',
        ),
        migrations.RemoveField(
            model_name='items',
            name='invoice',
        ),
        migrations.AddField(
            model_name='crmprojects',
            name='team',
            field=models.ManyToManyField(blank=True, related_name='project_team', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoice',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='invoice_related_items', to='crm.items'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='sub_total',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='items',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='items',
            name='fake_stars',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='items',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Product_Images/'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='notes',
            field=models.TextField(blank=True, default='This is a computer generated invoice no need signature', null=True),
        ),
        migrations.AlterField(
            model_name='items',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_type', models.CharField(blank=True, max_length=200, null=True)),
                ('quantity', models.IntegerField(default=1)),
                ('unit_price', models.FloatField(default=0.0)),
                ('sub_total', models.FloatField(default=0.0)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.invoice')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.items')),
            ],
        ),
    ]
